name: expense_app
services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      DEBUG_MODE: false
    networks:
      - application_network
    
  mongo_db:
    image: mongo:4.4.29
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - application_network
    command: --quiet
  
networks:
  application_network:
