name: expense_app
services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      DEBUG_MODE: false
    networks:
      - mongo_network
    
  mongo:
    image: mongo:4.4.29
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo_network
    command: --quiet
  
networks:
  mongo_network: