name: expense_app
services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    # ports:
    #   - "5000:5000"
    environment:
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      DEBUG_MODE: false
    networks:
      - application_network
      - proxy_network
  proxy:
    build:
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - proxy_network
  # proxy:
  #   image: nginx:stable-alpine3.19
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"
  #   networks:
  #     - proxy_network
  #   volumes:
  #     - ./nginx/:/etc/nginx/conf.d/:ro
  #     - ./src/templates:/usr/share/nginx/static:ro
  mongo_db:
    image: mongo:4.4.29
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - application_network
    command: --quiet
networks:
  application_network:
  proxy_network:
