name: expense_app
services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    environment:
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      DEBUG_MODE: false
    networks:
      - application_network
      - proxy_network
  mongo_db:
    image: mongo:4.4.29
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - application_network
    command: mongod --quiet --logpath /dev/null
  proxy:
    build:
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - proxy_network
networks:
  application_network:
  proxy_network:
