name: CI\CD pipeline

on: [push]

jobs:
  CI-CD-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install requirments for tests
        run: |
          pip install -r ./unit_tests/requirments.txt
 
      - name: Build image
        run: |
          docker compose build

      - name: Unit tests
        run: |
          docker run -d --rm --name server -p 5000:5000 expense_app-app:latest          
          pytest -v ./unit_tests/test_.py
          docker rm -f server
      
      - name: E2E tests
        run: |
          docker compose up -d
          pytest -v ./e2e_tests/test_.py
          docker conpose down -v
        