name: CI\CD pipeline

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9].[0-9]+'
  pull_request: 
    types: [opened, reopened ]



jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build image
        run: |
          docker compose build

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirments for tests
        run: |
          pip install -r ./unit_tests/requirments.txt
      - name: Unit tests
        run: |
          docker run -d --rm --name server -p 5000:5000 expense_app-app:latest          
          pytest -v ./unit_tests/test_.py
          docker rm -f server
      
      - name: E2E tests
        run: |
          docker compose up -d
          pytest -v ./e2e_tests/test_.py
          docker conpose down -v

  Publish:
    if: startsWith(github.ref, 'refs/tags/v')    
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{  secrets.GITHUB_TOKEN }}
      
      - name: Build image name
        id: image
        run: |
          image_registry=${{ env.REGISTRY }}
          image_name=$( echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          image_tag=
          echo "name=$image_registry/$image_name/$image_tag" >> $GITHUB_OUTPUT 
      
      - name: Publish
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.image.outputs.name }} 

