name: CI\CD pipeline

on: [push]

jobs:
  CI-CD-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: |
          docker-compose build

      - name: Unit tests
        run: |
          python --version
          # docker run -d --rm --name server -p 5000:5000 expense_app-app:latest
          

        