name: CI\CD pipeline

on:
  push:
    tags:
      - 'v[0-9]+.[0-9].[0-9]+'
  pull_request: 
    types: [opened, reopened ]



jobs:
  
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker compose build
      - name: Install requirments for tests
        run: |
          pip install -r ./e2e_tests/requirments.txt
        
      - name: E2E tests
        run: |
          docker compose up -d
          sleep 10
          pytest -v ./e2e_tests/test_.py
          docker conpose down -v

  Publish:
    if: | 
      startsWith(github.ref, 'refs/tags/v') ||
      github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{  secrets.GITHUB_TOKEN }}
      
      - name: Build image name
        id: image
        run: |
          image_tag=latest
          image_registry=${{ env.REGISTRY }}
          image_name=$( echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          if [[ "${{ github.ref_name }}" != "main" ]] && image_tag=${{ github.ref_name }}
          echo "name=$image_registry/$image_name/$image_tag" >> $GITHUB_OUTPUT 
      
      - name: Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.image.outputs.name }} 

